#!/bin/bash

# Attempt to load keys.
[[ -e ".env" ]] && . .env

[[ -v $TEST_KEY ]] || 'TEST_KEY is missing.' && exit 1
[[ -v $LIVE_KEY ]] || 'LIVE_KEY is missing.' && exit 1 

rm -r build/ cutegremlin.egg-info/ dist/
python3 setup.py sdist bdist_wheel
twine check dist/*

printf "\n\n"
read -p "Ready to push to test? (y/n)" -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u '__token__' -p "$TEST_KEY"

printf "\n\n"
read -p "Are you ready to publish? (y/n)" -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
fi
twine upload dist/* -u '__token__' -p "$LIVE_KEY"
